### ISSUE TITLE
Can not use paddle ocr using img2table

### ISSUE THREAD

**Issue by princeharish** [xavctn/img2table#100]
from img2table import paddleOCR
ocr = paddleOCR(lang="en")

ImportError: cannot import name 'paddleOCR' from 'img2table' (/usr/local/lib/python3.10/dist-packages/img2table/__init__.py)

I have installed paddlepaddle, paddleOCR and upgraded all module versions but no success. Please help.

**Comment by xavctn** [comment]
Hello,
Can you run `from paddleocr import PaddleOCR` and report the output ?

**Comment by princeharish** [comment]
Sure,
This time no compile time error, but during runtime kernel killed. after loading paddleOCR.
![image](https://github.com/xavctn/img2table/assets/12910354/92b7c99d-f926-439a-b29e-6c17997d1640)

**Comment by xavctn** [comment]
That's showing that the issue is not with this library but rather with your local installation of paddleocr.
You can check their github to see if they have a workaround.
