### ISSUE TITLE
How can I extract table together with texts under the table?

### ISSUE THREAD

**Issue by jonlimx** [xavctn/img2table#101]
Hi, is there a way to do so, like below picture. I would like to extract the table and text under the table

<img width="1192" alt="峰谷平2" src="https://github.com/xavctn/img2table/assets/9720225/8a77d737-bf94-463e-98c9-22b0df1f3b4d">

**Comment by jonlimx** [comment]
@xavctn could you please give me some suggestion?

**Comment by xavctn** [comment]
Hello,
No, it is not possible to get the text under the table straight from the package.

Somehow, for each table, you have the corresponding bounding box so you can do it by yourself by using it

**Comment by VishiK-on-github** [comment]
For getting some sort of context around the table the closest you could get right out of the box is the table title

**Comment by jonlimx** [comment]
> Hello, No, it is not possible to get the text under the table straight from the package.
> 
> Somehow, for each table, you have the corresponding bounding box so you can do it by yourself by using it

I see, I am not famaliar with ocr and the bounding box, then I will have to look into this.
