### ISSUE TITLE
PaddleOCR utilizing the whole memory

### ISSUE THREAD

**Issue by ahmshalan** [xavctn/img2table#102]
Machine specs:
CPU: 6 vcpus
MEMORY: 60 GB

I'm using the library to extract tables from images that are 200 dpi , and when I use the extract_tables method some times it works and other it utilize the whole memory which is 60 GB just to extract tables from 1 image Any ideas why this is happening.

Thanks!

**Comment by xavctn** [comment]
Hi,

Nope, never happened to me. As this is a paddleocr related issue, you should probably check with them.
