### ISSUE TITLE
Parsing Problems

### ISSUE THREAD

**Issue by hifiveszu** [xavctn/img2table#104]
Hello, this tool is amazing, the best I've found so far. 👍

I use it to extract tables from PDF files(**not Scanned PDFs**).  
If a file can be extracted(PDFs, not image), extraction will use `PdfOCR` (fitz/opencv);
If can't be extracted, extraction will use `OCR` (PaddleOCR/TesseractOCR...) It costs too much time 😭
```python
if not self._rotated and self.pdf_text_extraction:
    # Try to get OCRDataframe from PDF
    self.ocr_df = PdfOCR().of(document=self)
```

However, I have problems while using `PdfOCR` :
1. it separates table headers and rows into two separate tables.  Is it because the number of columns is inconsistent?
2. same strcuture of pdfs, one can extract tables and another one can't ,`PdfOCR` seems has some limit?

here's the code I used for parsing:
```python
extracted_tables = pdf.extract_tables(borderless_tables=True)
```

here's the log: 
```
column_groups: [DelimiterGroup(delimiters=[Cell(x1=1564, y1=104, x2=1603, y2=134, content=None), Cell(x1=131, y1=104, x2=164, y2=134, content=None), Cell(x1=67, y1=104, x2=93, y2=134, content=None), Cell(x1=382, y1=104, x2=1410, y2=134, content=None)], elements=[Cell(x1=93, y1=127, x2=131, y2=133, content=None), Cell(x1=1410, y1=104, x2=1564, y2=134, content=None), Cell(x1=164, y1=104, x2=382, y2=134, content=None), Cell(x1=98, y1=104, x2=127, y2=109, content=None)])]
table_rows: [TableRow(cells=[Cell(x1=1410, y1=104, x2=1564, y2=134, content=None), Cell(x1=164, y1=104, x2=382, y2=134, content=None)])]
borderless_table: <img2table.tables.objects.table.Table object at 0x7fc5c9c583a0>
{'img': array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8), 'tables': [], 'ocr_df': OCRDataframe(df=<LazyFrame [10 cols, {"page": Int64 … "y2": Int64}] at 0x7FC5D956EE20>)}
```
sometimes `identify_borderless_tables` can't detect the tables... 😂

Is it the problem some parameter value settings ? How can I handle this?  Thanks for your help 😊
Btw, the new version of PymuPDF already support `find_tables`, but it's not so good as `img2table`

**Comment by xavctn** [comment]
Hello,

Fyi, the table extraction is totally independent of the OCR, i.e the same tables will be extracted from a same document regardless of its type/extension. The OCR is just used at the end in order to the table content.

As of headers and all the rest, I know about those issues, I am currently working on an update of the algorithm order to get a more accurate and consistent extraction of borderless tables.

Somehow, it will probably never be 100% accurate

**Comment by hifiveszu** [comment]
@xavctn Thanks!
