### ISSUE TITLE
OSError: Tesseract not found in environment. Check variables and PATH

### ISSUE THREAD

**Issue by slychagin** [xavctn/img2table#109]
from img2table.ocr import TesseractOCR
import pytesseract

Path to Tesseract
`pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'`

Instantiation of OCR
`ocr = TesseractOCR(n_threads=1, lang="rus")`

This throw an error:
  File "D:\DataAscuisition\SeltingFGIS\venv\lib\site-packages\img2table\ocr\tesseract.py", line 56, in __init__
    raise EnvironmentError("Tesseract not found in environment. Check variables and PATH")
OSError: Tesseract not found in environment. Check variables and PATH

Teccerract was installed on Windows.

**Comment by slychagin** [comment]
I find the same issue

**Comment by xavctn** [comment]
Hello,

You have to properly update your environment variables. You can check the tesseract part of the Readme where I linked a tutorial for Windows.
