### ISSUE TITLE
Newline in table is not replaced by a space.

### ISSUE THREAD

**Issue by slychagin** [xavctn/img2table#110]
Hello! There is such a problem. Newline is not replaced by a space.

`pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'`

`ocr = TesseractOCR(n_threads=1, lang="eng", psm=11)`

`pdf = PDF(path_to_pdf,
          pages=[0],
          detect_rotation=False,
          pdf_text_extraction=True)`

`pdf.to_xlsx(dest='table.xlsx',
            ocr=ocr,
            implicit_rows=True,
            borderless_tables=False,
            min_confidence=50)`

![example](https://github.com/xavctn/img2table/assets/99026818/f9cd16d2-2e93-4f7a-b4e6-bdb0bd2677ec)

Result -> Hello my friendJohn

Maybe you know how to solve this?

**Comment by xavctn** [comment]
It works as intented, you have to click this button in Excel.

<img width="469" alt="image" src="https://github.com/xavctn/img2table/assets/90408365/d4204ab9-65af-4deb-8ed6-e6311cfe3c42">

**Comment by xavctn** [comment]
I did not allow return lines when formating data to excel.
I will add it

**Comment by xavctn** [comment]
Should be fixed in the latest release
