### ISSUE TITLE
Supporting rotation correction up to 90°

### ISSUE THREAD

**Issue by 4ka0** [xavctn/img2table#113]
First, thank you very much for creating a very useful project.
I'm currently using it with the Google Vision API and it is working quite well.

In my case, I am dealing with image files that sometimes contain tables that are quite wide and therefore appear on their side so as to fit within a portrait page. In other words, it is necessary to rotate the image by 90 degrees to correct the orientation of the table before trying to apply OCR to the image.
Would it be possible to support rotation correction up to 90° rather than the current 45°?

**Comment by xavctn** [comment]
Hello,

The implemented algorithm is designed to handle skew in image, not orientation.
You can apply rotations to the images yourself before calling the library. That is probably the best solution as of now.

**Comment by 4ka0** [comment]
Understood. Thank you very much for the reply.
