### ISSUE TITLE
Replace tables in the origin extract text 

### ISSUE THREAD

**Issue by hifiveszu** [xavctn/img2table#115]
Hello,

Thanks for your great work.
I'm working with PDF extraction. How can I replace the tables extracted by img2table with the "table section" in the text extracted by fitz?

**Comment by xavctn** [comment]
Hi,
I am sorry but I do not really get what you mean. Can you provide an example so that I can better comprehend your issue ?

**Comment by xavctn** [comment]
There is no direct way of doing it.

What you can do to achieve it is :
1. Retrieve the table bounding box which is computed on the page being converted to 200 dpi
2. Recompute this bounding box with coordinates corresponding to the page mediapox in pymupdf
3. When looping over your page text, discard elements that are within the table

That would look something like that:
``` python
doc = PDF("pdf_path")
tables = doc.extract_tables()

pdf = fitz.Document("pdf_path", filetype='pdf')
mat = fitz.Matrix(200 / 72, 200 / 72)

for idx, page_number in enumerate(range(pdf.page_count)):
    page = pdf.load_page(page_id=page_number)
    pix = page.get_pixmap(matrix=mat)

    # Get bbox of page tables
    page_tables = [(tb.bbox.x1 * page.mediabox[2] / pix.width, 
                    tb.bbox.y1 * page.mediabox[3] / pix.height, 
                    tb.bbox.x2 * page.mediabox[2] / pix.width, 
                    tb.bbox.y2 * page.mediabox[3] / pix.height)
                    for tb in tables.get(page_number)]
    
    for x1, y1, x2, y2, value, block_no, line_no, word_no in page.get_text("words", sort=True):
        matching_tables = [tb for tb in page_tables if x1 >= tb[0] and x2 <= tb[2] and y1 >= tb[1] and y2 <= tb[3]]
        if len(matching_tables) == 0:
            # Do whatever
```

**Comment by hifiveszu** [comment]
Thanks @xavctn You're really awesome and always willing to share and help others! 👍
