### ISSUE TITLE
How to extract the table and cell bbox coordinates along with its text content.

### ISSUE THREAD

**Issue by sathiyaajith** [xavctn/img2table#116]
ocr = TesseractOCR(n_threads=1, lang="eng")
pdf_tables = pdf.extract_tables(ocr=ocr, implicit_rows=True, borderless_tables=True, min_confidence=20)

i tried this but not able to extract the table and cell bbox coordinates along with its text content.

This is what i got as the Output:
{0: [ExtractedTable(title=AGENCY CUSTOMER ID:
LOC #:
ACORD
ADDITIONAL REMARKS SCHEDULE
Page
of, bbox=(51, 240, 1651, 439),shape=(4, 3)), ExtractedTable(title=ADDITIONAL REMARKS, bbox=(51, 473, 1651, 2089),shape=(3, 1))]}

I need the Table coordinate (x1,y1,x2,y2)
Cell coordinates within the table:[(x1,y1,x2,y2),(x11,y11,x22,y22)...]
Its corresponding text values inside the cell

**Comment by xavctn** [comment]
Hi,

You can access individual bounding boxes for each cell in the table by doing something like this :
```python
for id_row, row in enumerate(table.content.values()):
    for id_col, cell in enumerate(row):
        x1 = cell.bbox.x1
        y1 = cell.bbox.y1
        x2 = cell.bbox.x2
        y2 = cell.bbox.y2
        value = cell.value
```

**Comment by nissansz** [comment]
How to merge cells with rowspan and colspan? There are too many repeated cells for span cells.
