### ISSUE TITLE
EasyOcr Constructor refactor, enable customization of underline eazyocr instance

### ISSUE THREAD

**Issue by mikhailsnnt** [xavctn/img2table#117]
For convinienvce of usage much of EasyOcr features (e.g custom models), it woul'd be greate having ability to pass params of EasyOcr constructor

Maybe you'd consider to open branches for commiting. I think many of us would like to contribute. Thanks for your work great library 💯  🎉

**Comment by xavctn** [comment]
Hi,
Yep, it is definitely possible to allow constructor kwargs for all of the open-source OCRs.
I will update the code to do so.

Meanwhile, you can submit your contribution if you want using the "usual" way: fork --> PR. Otherwise, it would most likely get way too messy way too quick
