### ISSUE TITLE
`PaddleOCR` assumes that the OCR result is an unpackable list

### ISSUE THREAD

**Issue by rytheranderson** [xavctn/img2table#118]
Hello, thanks for this great repo - I'm glad you have taken the time to implement multiple OCR engines.

Currently, the `PaddleOCR.hocr` method assumes that the OCR result can always be unpacked, which is not always the case. For example, for an empty image `PaddleOCR.orc` returns a list with `None`s resulting in a `TypeError` at the return line: https://github.com/xavctn/img2table/blob/2d35923fc044d65db19c22a984183cc369c97429/src/img2table/ocr/paddle.py#L61

See this snippet from `paddleocr`: https://github.com/PaddlePaddle/PaddleOCR/blob/673c95262b76ac48c3d37d45a542bb2dd8dcfd1b/paddleocr.py#L669C1-L671C29

Here is some code to reproduce (image used is attached):
```python
from img2table import document
from img2table.ocr import PaddleOCR


ocr_engine = PaddleOCR(lang="en")
extract_doc = document.Image("empty.png")
tables = extract_doc.extract_tables(ocr=ocr_engine, borderless_tables=False)
```
![empty](https://github.com/xavctn/img2table/assets/43506100/49dd11a9-39e4-4081-b1a2-375b44fc8033)

I am using
```bash

pip list | grep "paddle"
paddle-bfloat                      0.1.7
paddleocr                          2.7.0.3
paddlepaddle                       2.5.1
```

With `img2table 1.2.1`

**Comment by xavctn** [comment]
Hello,

Thanks for the feedback, I will fix that along with other modifications.
Should be patched soon
