### ISSUE TITLE
Get wrong columns of the table

### ISSUE THREAD

**Issue by ocrifydotnet** [xavctn/img2table#119]
When I used below image then the result is next table
![grid1](https://github.com/xavctn/img2table/assets/110530092/e8529a0f-767e-41dd-a7a1-863be1f3c20b)
<html>
<body>
<div align="center" style="color: rgb(213, 213, 213); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(56, 56, 56); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

  | 0 | 1 | 2 | 3 | 4
-- | -- | -- | -- | -- | --
Earnings | Amount | Deductions | Amount |  
Basic | 10000 | Provident Fund |   | 1200
Incentive Pay | 1000 | Tax |   | 500
House Rent Allowance | 400 | Loan |   | 400
Meal Allowance | 200 |   |   |  
Total Earnings | 11600 | Total Deductions |   | 2100
  |   | Net Pay |   | 9500

</div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by xavctn** [comment]
Hello,

I was not able to replicate your issue, the library seems to be working fine on my end.
<img width="363" alt="image" src="https://github.com/xavctn/img2table/assets/90408365/ef146c15-772f-4aa6-bbb6-3efe73509319">

Are you using the latest release ?

**Comment by ocrifydotnet** [comment]
I've used Doctr.

I will use the tesseractocr

**Comment by restaurant365-sdinh** [comment]
![grid3](https://github.com/xavctn/img2table/assets/99938067/560d7ce8-ce7e-4f0f-8da6-4f1b62023330)
It's wrong with the image

**Comment by restaurant365-sdinh** [comment]
The scripts to install:
```
pip install git+https://github.com/xavctn/img2table
pip install PaddleOCR
pip install paddlepaddle==2.4.2
```

The code:
```
from img2table.ocr import PaddleOCR

ocr = PaddleOCR(lang='en')
from img2table.document import Image

src='/content/grid3.jpg'
# Instantiation of document, either an image or a PDF
doc = Image(src)

# Table extraction
extracted_tables = doc.extract_tables(ocr=ocr,
                                      implicit_rows=False,
                                      borderless_tables=True,
                                      min_confidence=50)
```

**Comment by xavctn** [comment]
This is because the table has a big enough gap between the last column header and its values that makes the algorithm detect it as two different columns.

<img width="783" alt="image" src="https://github.com/xavctn/img2table/assets/90408365/d990e0d9-2aa1-41f2-9061-dab89dc33ace">
