### ISSUE TITLE
Skipped single-digt numbers

### ISSUE THREAD

**Issue by zhywang17** [xavctn/img2table#124]
Thank you for this handy tool!
When I try to use TesserOCR to convert the following table from a PDF file, all the single-digit numbers are skipped. 
![image](https://github.com/xavctn/img2table/assets/32022780/978c6d7b-3e9c-47a5-b2d7-1e5334c47b5e)

The resulting table is:
<html>
<body>

  | 0 | 1 | 2 |
-- | -- | -- | -- 
Example\nnumber | FGFR1 Binding\nICso (nM) | FGFR2 Binding\nICso (nM) | FGFR3 Binding\nICso (nM)
None | 44 | ND | None
None | 42 | ND | None
None | 47 | ND | None
None | 157 | ND | 18
None | 52 | ND | None
None | 73 | ND | None
None | 56 | ND | None
10 | 56 | ND | None
11 | 210 | ND | 25
12 | 214 | ND | 32
13 | 245 | ND | 39

</body>
</html>

Any idea why would this happen? Is there any configuration that can save this issue?

**Comment by bakerb15** [comment]
I have had similar experience. It gets some of the single digits. The quality of the scanned pdf I'm attempting process is pretty good to so there must be something else going on. Unsure if the bug is oce language model dependent. I was thinking it was an issue with Tessaract.

**Comment by xavctn** [comment]
This is because of Tesseract character detection as it works fine when I try using other OCR solutions on your image.

Messing with the PSM configuration can be an option as digits are detected when using `ocr = TesseractOCR(lang='eng', psm=1)`

**Comment by zhywang17** [comment]
I tried easyOCR and it gets much better now. Thanks!
