### ISSUE TITLE
Better results when running individual pages

### ISSUE THREAD

**Issue by bakerb15** [xavctn/img2table#125]
I have large pdfs i'm processing. I found I get way better results if I chop the pdf into individual pages. Using the pages parameter with the PDF constructor doesn't give you same results as running a single page. I may have some ideas for a new feature to help with this.

**Comment by xavctn** [comment]
Hello,
This is not normal as each PDF page is converted to an image and is supposed to be processed independently of each other.

Open to hear what you think can be done to address it.
My best guess would be that here might be some mutable objects hanging in the code and messing up table detection after the first page/image.

As I've never encountered this issue, are you able to provide an example ?

**Comment by bakerb15** [comment]
Sorry, at the moment I can't provide an example. I'm unable to upload these pdfs due to privacy concerns. I'll see if I can get you more info though.

I resorted to using a command line utility to split the pdfs into individual pages, generating a xlsx for each and then combining the results with another program.
