### ISSUE TITLE
Unable to extract tables from a image-based pdf file

### ISSUE THREAD

**Issue by yadavaalok** [xavctn/img2table#127]
I am trying to extract tables from a pdf which have text-based tables and image-based tables as well, but it is only able to extract text-based tables not image-based table. I have refered [this](https://github.com/xavctn/img2table/blob/main/examples/Basic_usage.ipynb) example to do that.

Please guide me to this as I am very new to this.

Thanks!!

**Comment by damaocode** [comment]
could you share the procedure of you operation?

**Comment by xavctn** [comment]
Hello,

I do not understand what you mean by "text-based tables" and "image-based tables". Can you share an example of what you're trying to do ?

**Comment by damaocode** [comment]
> Hello,
> 
> I do not understand what you mean by "text-based tables" and "image-based tables". Can you share an example of what you're trying to do ?

Hello，I guess what he said is that some PDF files can be copied with the mouse, while others cannot be copied with the mouse

**Comment by yadavaalok** [comment]
> > Hello,
> > I do not understand what you mean by "text-based tables" and "image-based tables". Can you share an example of what you're trying to do ?
> 
> Hello，I guess what he said is that some PDF files can be copied with the mouse, while others cannot be copied with the mouse

Yes you get it.

**Comment by damaocode** [comment]
> > > Hello,
> > > I do not understand what you mean by "text-based tables" and "image-based tables". Can you share an example of what you're trying to do ?
> > 
> > 
> > Hello，I guess what he said is that some PDF files can be copied with the mouse, while others cannot be copied with the mouse
> 
> Yes you get it.

"Thank you  for your affirmation! We look forward to the author's support."

**Comment by xavctn** [comment]
Ok,
There are no differences between native and "scanned" PDF files, the processing done by the library in order to identify tables will be exactly the same.

However, you will have to provide an OCR if you want to parse the table content for "scanned" PDFs. On native PDFs, text is directly extracted from the file

**Comment by damaocode** [comment]
> Ok, There are no differences between native and "scanned" PDF files, the processing done by the library in order to identify tables will be exactly the same.
> 
> However, you will have to provide an OCR if you want to parse the table content for "scanned" PDFs. On native PDFs, text is directly extracted from the file

Thank you, I got it
