### ISSUE TITLE
Table is not detected when border is dotted line

### ISSUE THREAD

**Issue by swidbar01** [xavctn/img2table#128]
Hi,
When **table border is made of dotted line**, table is not detected and I am having no results.
Is there any easy fix to this issue?
Example of PDF: [Serial Number_largeDot_public.pdf](https://github.com/xavctn/img2table/files/13164422/Serial.Number_largeDot_public.pdf)
Thanks

Part of the code used:
_ocr = VisionOCR(timeout=120)
doc = PDF(path)
extracted_tables = doc.extract_tables(ocr=ocr,
                                      implicit_rows=True,
                                      borderless_tables=True,
                                      min_confidence=25)_

**Comment by xavctn** [comment]
Hello,
As of now, there is no simple fix for it. I already have a code that is supposed to handle dotted lines but it can be improved.
I am going to check what I can do on those types of borders.
