### ISSUE TITLE
PaddleOCR

### ISSUE THREAD

**Issue by taikai-zz** [xavctn/img2table#129]
python3.11
python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
pip install "paddleocr>=2.0.1"     
pip install img2table[paddle]       
normal setup
execute
>>> from img2table.ocr import PaddleOCR
Illegal instruction (core dumped)
May I ask how to solve it

**Comment by taikai-zz** [comment]
>>> from utils import display_borderless_tables
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'utils'

**Comment by xavctn** [comment]
> python3.11 python3 -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple pip install "paddleocr>=2.0.1" pip install img2table[paddle] normal setup execute
> 
> > > > from img2table.ocr import PaddleOCR
> > > > Illegal instruction (core dumped)
> > > > May I ask how to solve it

This is an issue with your installation of PaddleOCR, not with the library. I think that it is an hardware issue where some CPUs are not working

**Comment by xavctn** [comment]
> > > > from utils import display_borderless_tables
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > ModuleNotFoundError: No module named 'utils'

The utils file is just part of the examples and not of the library, that's why it is not working for you
