### ISSUE TITLE
extract tables 

### ISSUE THREAD

**Issue by hifiveszu** [xavctn/img2table#133]
Hello,

I encountered the following issues while using img2table to parse PDF tables:

1. The table structure recognition is not accurate, and it cannot identify the headers of the table. Is there any way I can adjust this?

```python
from img2table.document import PDF
doc = PDF(pdf_path)
tables = doc.extract_tables(borderless_tables=True, min_confidence=70)
```

result file: [2309.10305.md](https://github.com/xavctn/img2table/files/13372749/pdf.md)
source pdf: [2309.10305.pdf](https://github.com/xavctn/img2table/files/13372757/2309.10305.pdf)

2. When there are a large number of pages(maybe 300 pages) in the PDF, the parsing time is significantly longer (since each page needs to be processed using OpenCV). Do you have any suggestions to speed up the parsing process? (I have considered using multiprocessing or similar methods for handling the task.)

**Comment by xavctn** [comment]
Hi,

I published a new release of the library where I have made some updates/adjustments to the algorithm.
In your first file, table detection should be better.

In terms of speed, I made some optimization to the code that should now run 2 to 4x faster. When it comes to large PDFs, the issue can also be (other than the opencv processing time) that I am caching all images corresponding to each page. It might have some unwanted side-effects on large PDFs, I will have to check

**Comment by hifiveszu** [comment]
Thanks @xavctn 😊
I tried the new release and found that header parsing has improved significantly, and the speed has also increased a lot. 👍 

I have one more small issue: 
On page 12 of the file I've uploaded.
img2table recognized the table on page 12, but it couldn't extract the text, possibly due to a certain degree of text tilt or rotation. 😂
![image](https://github.com/xavctn/img2table/assets/15151837/b51e4684-8c81-4128-92b2-05e103ab990d)

**Comment by hifiveszu** [comment]
Thanks for your answer. I understand what you mean! 
I checked the word coordinates and found that they are within the table area, but they are missing from the table extracted. I'll need to find another way to fill it in. 😂
Thank you once again for your generous preaching. 👍 @xavctn

**Comment by xavctn** [comment]
Hello,
I do not think that this is related to the latest release but more likely a latent issue in the algorithm.
I will keep this in mind in order to improve the content segmentation into rows but I cannot promise anything as I do not have, as of now, a clear idea of how to implement a better solution.

**Comment by hifiveszu** [comment]
@xavctn Thanks!

**Comment by xavctn** [comment]
Hi,
I made some modifications that should solve the issue and will be contained in the next release 👍

**Comment by hifiveszu** [comment]
@xavctn Amazing! 😄

**Comment by hifiveszu** [comment]
Hi @xavctn 
I tried the new version. The table column recognition still has some errors and misalignments (the previous version was performing better, maybe due to modifications in the recognition algorithm's parameters). There are also duplicate rows (not a significant issue).

Accurate parsing is quite challenging, and the algorithm is also difficult 😂.
