### ISSUE TITLE
Unable to extract text in table when table is in the table

### ISSUE THREAD

**Issue by xxleonn** [xavctn/img2table#136]
from img2table.document import Image
from img2table.ocr import PaddleOCR

ocr = PaddleOCR()
img = Image(f"img.png")
img.to_xlsx(f"Table.xlsx", ocr = ocr, implicit_rows = False, borderless_tables = False, min_confidence = 1)
extracted_table = img.extract_tables(ocr = ocr, implicit_rows = False, borderless_tables = False, min_confidence = 1)

![image](https://github.com/xavctn/img2table/assets/127380750/c3045099-8da9-4df2-b978-bccc223105b3)

when I executed the code above, I was unable to detect the text in the 4th column, 2nd row of my table, given my column cell is with a table inside.
It return the table as 2nd table only, and not extracting the text. Do you have any suggestion to extract the text I am looking for in the table?

**Comment by xxleonn** [comment]
resized_image = pil_image.resize((int(pil_image.width ), int(pil_image.height )), resample = PILImage.LANCZOS)

Furthermore when I do not change the size of image, img2table can perform extraction.

resized_image = pil_image.resize((int(pil_image.width * 1.1), int(pil_image.height * 1.1)), resample = PILImage.LANCZOS)

This code, produce large image but OCR failed to extracted the table.

**Comment by xavctn** [comment]
Hello,

TBH, I am not really sure what is your issue with this.

This is the kind of table that I would get with your input :
The "included" table is detected as rows of the general table, but I would say that it is logical given the input image.

![download](https://github.com/xavctn/img2table/assets/90408365/3d2ec503-1181-4cd4-93c9-3fe71ff80d39)

To be able to help you more precisely, I'll need the actual file to be able to examine it

**Comment by xxleonn** [comment]
Hello, 

Thank you for the reply, for this given pdf,
[SampleTable.pdf](https://github.com/xavctn/img2table/files/13445817/SampleTable.pdf)

I ran code below and it give me the Table as per the excel table 1 and image below, 
the observation column is unable to be extracted.

[TableExample2.xlsx](https://github.com/xavctn/img2table/files/13445819/TableExample2.xlsx)

![image](https://github.com/xavctn/img2table/assets/127380750/73c9c2d8-e061-444c-bf64-56cc1947a29e)

`
ocr = PaddleOCR(lang="en",
                kw={
                    'ocr_version': 'PP-OCRv3',
                    'structure_version': 'PP-StructureV2',
                    'det_model_dir': './Python_V10/PaddleOCR/ch_PP-OCRv3_det_infer',
                    'rec_model_dir': './Python_V10/PaddleOCR/en_PP-OCRv3_rec_infer',
                    'cls_model_dir': './Python_V10/PaddleOCR/ch_ppocr_mobile_v2.0_cls_infer',
                    'table_model_dir': './Python_V10/PaddleOCR/en_ppstructure_mobile_v2.0_SLANet_infer',
                    'layout_model_dir': './Python_V10/PaddleOCR/picodet_lcnet_x1_0_fgd_layout_infer',
                    'lang': 'en',
                })

doc = fitz.open("SampleTable.pdf")
page = doc[0]
image = page.get_pixmap(matrix=fitz.Matrix(100, 100), dpi = 1800)
pil_image = PIL.Image.frombytes("RGB", (int(image.width), int(image.height)), image.samples)
resized_image = pil_image.resize((int(pil_image.width * 1.05), int(pil_image.height * 1.05)), resample = PIL.Image.LANCZOS)
success, encoded_image = cv2.imencode('.png', np.array(resized_image))
image_bytes = encoded_image.tobytes()
img = Img2Table.Image(image_bytes)
img.to_xlsx(f"TableExample2.xlsx", ocr = ocr, implicit_rows = False, borderless_tables = False, min_confidence = 0)
extracted_table = img.extract_tables(ocr = ocr, implicit_rows = False, borderless_tables = False, min_confidence = 0)
display_html(extracted_table[0].html_repr(title = 'Result'), raw = True)
`

**Comment by xavctn** [comment]
I've checked this case and I will make some modifications so that the larger table is properly detected

**Comment by xxleonn** [comment]
Thanks for the reply.
I do enlarge in this case because I found some very small image, it cannot detect all the words in the table. However when I enlarge (resize) the image, the table extraction is failed too, I guess I over enlarged the image.
Thank you for the help!

**Comment by xavctn** [comment]
Hi,

I made some modifications/adjustments to the code in the latest release, your case should now be working as expected.
At least, the example you gave me is now properly processed.
