### ISSUE TITLE
Tesseract not found in environment

### ISSUE THREAD

**Issue by ansuma-basumatary** [xavctn/img2table#137]
I am trying to use img2table Tesseract OCR in Windows through conda.
I have already installed the Tesseract  OCR for windows from the link [here](https://github.com/UB-Mannheim/tesseract/wiki)
But I am getting the following error when I try to run the following snippet:
    `import pytesseract`
    `from img2table.ocr import TesseractOCR`
    `from img2table.document import Image`
    `ocr = TesseractOCR(n_threads=1, lang="eng")`

`OSError: Tesseract not found in environment. Check variables and PATH`

Could someone tell me what I may be doing wrong?

**Comment by xavctn** [comment]
Hello,
Please check the Tesseract part of the documentation where a tutorial for windows users is inked.
