### ISSUE TITLE
Can't Identify this image a table and can't extract the data

### ISSUE THREAD

**Issue by Jainu-s** [xavctn/img2table#139]
When given table it giving me one column and one row only.

![image_18](https://github.com/xavctn/img2table/assets/59506207/e178b3d0-1ba7-4ce5-bea0-52e9f4c73de2)

Can you help me on it.

**Comment by xavctn** [comment]
Hi,
You can set the `borderless_tables` parameter to True in order to identify tables where cells are not defined by solid lines

![download](https://github.com/xavctn/img2table/assets/90408365/021bcb33-0cc3-45b3-a44f-ef48c8ead33b)
