### ISSUE TITLE
[bug] Having table structure but no ocr_res

### ISSUE THREAD

**Issue by luan78zaoha** [xavctn/img2table#142]
The detected images show a table structure, but the OCR is not recognizing any text and is throwing an error.

https://github.com/xavctn/img2table/blob/2fc42c2f229de40156d642c8ce369e5fdb6ad86c/src/img2table/document/base/__init__.py#L85C10-L85C10
Now, self.ocr_df is None.

lang='ch'

![0](https://github.com/xavctn/img2table/assets/32391999/ce4d9d4f-3024-484a-9fa5-bd8d32f492a8)
Error: 'NoneType' object has no attribute 'page'

**Comment by xavctn** [comment]
Hello,
I will modify it in order to avoid this error if the OCR has not been able to detect any word in the document by simply returning no tables.
Thanks for the feedback
