### ISSUE TITLE
Extracted table is returning contents for empty cells

### ISSUE THREAD

**Issue by xansrnitu** [xavctn/img2table#146]
Hi,
I am having an issue where in if i have a row having only the first column(cell) populated but all the remaining columns of the same row are empty, the first col cell's value is being returned for all the empty cells as well. Here is my code -
```
ocr = EasyOCR(lang=["en"])
img = Image2(src=img_path)
tables = img.extract_tables(ocr=ocr, implicit_rows=True)      
table=tables.pop()
table.df

```
Is it possible to not have this behaviour? I want the empty cells to return empty(no) value.

I have attached both the source image and output screenshot.
![issue](https://github.com/xavctn/img2table/assets/63858582/a82c4a79-6193-4f85-8006-d44de05770db)
![table1](https://github.com/xavctn/img2table/assets/63858582/1a29efff-fe7f-4575-9622-c6d027c1e037)

Thank you for this useful library!

**Comment by xavctn** [comment]
Hello,
This is most likely because the vertical lines in the second row failed to be detected.

Are you able to provide the original document so that I can take a look at what is going wrong ?

**Comment by xansrnitu** [comment]
Hi @xavctn ,
Sure. 
Here it is.
[source.pdf](https://github.com/xavctn/img2table/files/13860917/source.pdf)
Thanks for having a look!

**Comment by xavctn** [comment]
Hello,
I have created a new release that fixes the issue, it should be good now.
Xavier
