### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by shivam-alraedah** [xavctn/img2table#153]
While automating document parsing using img2table[paddleocr], I encountered challenges in loading weights locally from my host machine instead of downloading them from the internet every time. It would be beneficial to enhance the documentation with specific guidelines for this common use case. This addition would assist users, especially those deploying it on Docker, in easily referencing steps to pull weights offline and seamlessly integrate them into their code.

**Comment by shivam-alraedah** [comment]
i can take this up. along with this since i have done enough work to make this containerized for experimentation just with single command. i can add those steps too. that will increase the easy adaptation.

**Comment by xavctn** [comment]
Hello,

IMO, this is not related to this library but rather to PaddleOCR and containerization.
You just have to include model files within your image and reference their locations with the proper arguments when instantiating the OCR object.

There are no specificity related to this library when it comes to containerization so it does not make sense to include anything in the documentation regarding this topic.

Thanks for the feedback nonetheless.
