### ISSUE TITLE
Can't extract borderless table

### ISSUE THREAD

**Issue by CatherineBogorada** [xavctn/img2table#158]
Hi guys! Thank you for a great package!

But I have an issue with my pdf. Here is the result of tables detection:
![image](https://github.com/xavctn/img2table/assets/12482472/3340155e-ab91-4d01-9468-b4db253f4f14)
![image](https://github.com/xavctn/img2table/assets/12482472/f32c30be-0eb6-4ff1-8d90-90d0734f50f7)

most of table information detected properly, but bottom table on the first page didn't.

I've tried to remove top information in such way: 
![image](https://github.com/xavctn/img2table/assets/12482472/a3691e5d-9db1-42cf-856f-63ee9a31e144)

and apply detection to this image but it didn't help.

Here is my code:

```
from img2table.document import PDF
from img2table.ocr import TesseractOCR

pdf = PDF(src=f'data/{input_files[26]}.pdf')

tesseract_ocr = TesseractOCR(n_threads=2, lang="ukr+eng+rus")

pdf_tables = pdf.extract_tables(ocr=tesseract_ocr,
                                implicit_rows=True,
                                borderless_tables=True,
                                min_confidence=50)
```

and here is an initial pdf ([Код: 104715.pdf](https://github.com/xavctn/img2table/files/13904350/104715.pdf)). Would be very grateful if you have a look!

**Comment by xavctn** [comment]
Hello,
The algorithm implemented as of now relies on "continuous" vertical whitespaces in order to identify column delimiters.
In your case, as there are some text blocks in the middle of the table, it fails to detect the columns.

I will check if I can modify it in order to handle those kind of cases but I cannot promise anything

**Comment by xavctn** [comment]
Hi,
A new release has been published and should haved fixed some of those issues with "discontinuous" columns.
