### ISSUE TITLE
Unable to install form pip

### ISSUE THREAD

**Issue by jimtk-dev** [xavctn/img2table#17]
Trying to use your package img2table. After pip install from pypi I only get the dist_info folder and no img2table code.
I'm on windows 10 if it make any difference. 
Result from simple code is: 

Traceback (most recent call last):
  File "D:\source\image_table\main.py", line 6, in <module>
    from img2table.document import PDF, Image
ModuleNotFoundError: No module named 'img2table'

The venv\Lib\site-packages folder has no code  (nor a folder) for img2table: Here's a listing:
```

venv
    Lib
       site-packages
            _distutils_hack
            beautifulsoup4-4.11.2.dist-info
            bs4
            bs4-0.0.1.dist-info
            cv2
            dateutil
            fitz
            img2table-0.0.8.dist-info
                INSTALLER
                LICENSE.txt
                METADATA
                pbr.json
                RECORD
                REQUESTED
                top_level.txt
                WHEEL
            numpy
            numpy-1.24.2.dist-info
            opencv_python-4.7.0.68.dist-info
            pandas
            pandas-1.5.3.dist-info
            ....
             other files (no img2table present)
            .... 
```

Thank you!

**Comment by xavctn** [comment]
Hi,

I checked and it was an issue with the creation of the wheel with pbr.
Just fixed it and tested it, should be good now.
I am going to publish a new release ASAP today.

**Comment by xavctn** [comment]
Fixed, you can install version 0.0.9

**Comment by jimtk-dev** [comment]
Thanks. It now works....

Encountered another problem. Do you prefer I open another issue?

problem is in venv/Lib/site-packages/img2table/ocr/__init__.py

Where it tries to import all ocr packages, which results in missing libraries (aws boto3, azure, etc).
I was able to move forward by simply commenting out the packages I did not need and kept Tesseract (default)

### mg2table/ocr/__init__.py

```
# coding: utf-8

# from img2table.ocr.aws_textract import TextractOCR
# from img2table.ocr.azure import AzureOCR
# from img2table.ocr.google_vision import VisionOCR
from img2table.ocr.tesseract import TesseractOCR   
```

**Comment by xavctn** [comment]
I've fixed it as well. I will create yet another realease
