### ISSUE TITLE
How can I import an image which is already read as numpy.ndarray?

### ISSUE THREAD

**Issue by ibowennn** [xavctn/img2table#174]
Thank you for your work!

Before importing the image into img2table, I need to preprocess it. This involves reading the image as a numpy.ndarray format and split it into several tables. 
I received a "TypeError: Invalid type <class 'numpy.ndarray'> for src argument" when attempting to pass the images into the Image API. How can I import these numpy.ndarray images into img2table?

**Comment by xavctn** [comment]
Hello,

You can use an image array as such:
```python
_, buffer = cv2.imencode(".jpg", img)
doc = Image(src=BytesIO(buffer))
```
