### ISSUE TITLE
polars.exceptions.ColumnNotFoundError: overlapping_x

### ISSUE THREAD

**Issue by Akashepi** [xavctn/img2table#196]
Yesterday the below code was working but from today, I'm facing the issue given below.

Code: 
doc = Image(src)

doc.to_xlsx(dest='table3.xlsx',
            ocr=ocr,
            implicit_rows=True,
            borderless_tables=False,
            min_confidence=50)
            
Issue: return wrap_df(ldf.collect(callback))
polars.exceptions.ColumnNotFoundError: overlapping_x

**Comment by aigy0828** [comment]
Me too！

**Comment by keidikapllani** [comment]
Experiencing this issue as well, Img2Table Version: 1.2.11, Ventura 13.6.6, Python 3.11.5

**Comment by xavctn** [comment]
Hi,
I suspect that it is caused by the latest release of the polars package.
You can try to install polars==0.20.26 and it might be working.

I will check it tonight after work and release a fix ASAP

**Comment by RadeenXALNW** [comment]
Just change the polars package version. Some optimization problem has been arisen with their latest version.
![image](https://github.com/xavctn/img2table/assets/66905164/8cfd12cd-74d1-455c-8bdf-cb42d5d1bfc2)

**Comment by folk-digital** [comment]
> Just change the polars package version. Some optimization problem has been arisen with their latest version. ![image](https://private-user-images.githubusercontent.com/66905164/333220790-8cfd12cd-74d1-455c-8bdf-cb42d5d1bfc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzcxOTIsIm5iZiI6MTcxNjQ3Njg5MiwicGF0aCI6Ii82NjkwNTE2NC8zMzMyMjA3OTAtOGNmZDEyY2QtNzRkMS00NTVjLThiZGYtY2I0MmQ1ZDFiZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE1MDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOTljMzM4ODhlNjFjMjA4ZjNjZWM3YmFhMDdkMzAwYzQwN2I0Mzc1NGViZGFiM2RhNTk4ZTU2MDIyMDJlZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7IP5t4XvXfcjw4G66OwzYemFyT8zMqZ6Rs-eZm6RcJM)

Solved it for me!👏🏾 You just saved my job!😅 Thanks!

**Comment by Akashepi** [comment]
> Just change the polars package version. Some optimization problem has been arisen with their latest version. ![image](https://private-user-images.githubusercontent.com/66905164/333220790-8cfd12cd-74d1-455c-8bdf-cb42d5d1bfc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzI0NzAsIm5iZiI6MTcxNjUzMjE3MCwicGF0aCI6Ii82NjkwNTE2NC8zMzMyMjA3OTAtOGNmZDEyY2QtNzRkMS00NTVjLThiZGYtY2I0MmQ1ZDFiZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA2MjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NmI5ZDcwM2ViZTk0YjBhMTA0ZWEzNGEwYTM1MWU3NWNhYjlkM2JhODQxMjA3NjE0ZjE3M2MyYjU2MmY3ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BCQ54rwY5c-GZbAsTxaDyYkkMuvWOtNrguqWlclCSpU)

Still facing same issue, please provide your python version as well

**Comment by Ahdw** [comment]
<img width="626" alt="polars" src="https://github.com/xavctn/img2table/assets/6417649/d3af84d1-d75f-43fc-9302-f7621a7e33dc">

I am using `Python 3.11.6` 

I've met the same issue, and I solved it by installing an older version of `polars`.

**Comment by arunprasadd** [comment]
Solved for me as well. Thanks

**Comment by Akashepi** [comment]
Solved
