### ISSUE TITLE
Grey highlighted format issue

### ISSUE THREAD

**Issue by alakade-newageproducts** [xavctn/img2table#24]
I have tried both OCR techniques Tesseract and Paddle to extract tables from the pdf page, they are not able to extract grey highlighted text values, except for this one they have extracted correct information from each of the tables. 

any suggestions?

![image](https://user-images.githubusercontent.com/75308420/221374411-f04c0ab2-2f58-4817-96b4-4a0d8ccd42dc.png)

**Comment by xavctn** [comment]
Hi,

This can be caused by 2 things :
- The OCR is not able to pick up text on this specific row because of the background
- The algorithm detecting table cells fails to detect this line for some reasons

Is it possible for you to provide the file used so that I can assess what the cause is ?

**Comment by alakade-newageproducts** [comment]
sure. here is the sample file.

sample 2 has multiple tables but any of the OCR is not able to pick up any table. It is only picking up the table on the last page.

Thank you for your response.

[sample1.pdf](https://github.com/xavctn/img2table/files/10833406/sample1.pdf)
[sample2.pdf](https://github.com/xavctn/img2table/files/10833407/sample2.pdf)

**Comment by xavctn** [comment]
After some investigations, it had nothing to do with the grey background, there is a bug in the algorithm.

I am working on a fix

**Comment by alakade-newageproducts** [comment]
> After some investigations, it had nothing to do with the grey background, there is a bug in the algorithm.
> 
> I am working on a fix

Thank you. let me know if I can help you with anything.

**Comment by xavctn** [comment]
It is fixed, I have published a new version of the package integrating it
