### ISSUE TITLE
self.ocr_df.text_size is none

### ISSUE THREAD

**Issue by gracew99** [xavctn/img2table#29]
Hi, I'm processing a bunch of images with img2table but some of them hit the error below. The error seems to occur on small images like below which is a silly example but I was wondering if there could be a fix for this error? Thanks!

![jim (2)_7](https://user-images.githubusercontent.com/29738504/223329416-90adca97-74a8-4868-bfba-edc5a70c02e7.png)
![image](https://user-images.githubusercontent.com/29738504/223329580-58d74905-ad6a-4a10-a74b-a2f8327b041d.png)

**Comment by xavctn** [comment]
Hi, this error is on my end when no text is detected by the OCR.
I just patched it on the main branch and will include it in the next release.
