### ISSUE TITLE
Using Colab But running since 1.5 hour

### ISSUE THREAD

**Issue by arnavmehta7** [xavctn/img2table#34]
Hi, I am using this amazing tool to convert a 600 pages data to a table using gcp vision API. However it's processing since a lot of time 
![image](https://user-images.githubusercontent.com/65492948/227967124-5573536d-ef73-47b2-92ac-2869a119c642.png)
Is this normal?

**Comment by arnavmehta7** [comment]
> When it comes to processing time, it is mostly related to the OCR time rather than the table detection computation time. I will do some checks to verify if something is not working as intended when using PDFs.

@xavctn In first line you wrote that the GCP API is not called, then in next line you wrote `it is related to OCR time`. So if I am not using GCP OCR by using PDFs, then how it is taking so much time?

**Comment by arnavmehta7** [comment]
Do you have a mail? I can email there, rather than send here.

**Comment by xavctn** [comment]
xav.canton@gmail.com

**Comment by arnavmehta7** [comment]
Is there any way to specify **not to use PyMuPDF?**

**Comment by xavctn** [comment]
In the current version of the library, no it is not possible.
And I'd rather fix it than drop it because retrieving the document text should be way faster than with an OCR and 100% accurate.

If you want to drop it, you can clone the project and remove [this line](https://github.com/xavctn/img2table/blob/main/src/img2table/document/pdf.py#L47)

**Comment by arnavmehta7** [comment]
Oh, too late lol. I converted each pdf page to a .png and ran the code. Worked almost perfectly except for one file. Amazing stuff appreciate it!

**Comment by xavctn** [comment]
Thanks !
I fixed the speed issue with large PDF files. When it comes to the questiomark characters, I can't really do anything about it as of now.
