### ISSUE TITLE
Cannot Extract without visible rows. 

### ISSUE THREAD

**Issue by arnavmehta7** [xavctn/img2table#37]
![143](https://user-images.githubusercontent.com/65492948/228431352-5d77ae1b-8c1d-492a-8934-e9796ac37d93.png)
Hey, I was processing one more Image. Whether I write implicit_rows=True or False, it always returns a empty dataframe. I'm wondering if such image could be processed through this?

**Comment by xavctn** [comment]
Hi,

This is what I call a borderless table. They can be detected by setting `borderless_tables=True` in the `extract_tables` method.
The implemented method is not 100% reliable so detection of those kind of tables is disabled by default.

I would advise you to use version 0.0.20 of the package that I released yesterday as I redid completely the algorithm for those tables

**Comment by arnavmehta7** [comment]
I ran this code today on my colab notebook, so I think I am using the latest version

**Comment by arnavmehta7** [comment]
I see, I will try your suggestion
