### ISSUE TITLE
Unexpected keyword with Polars from_dict

### ISSUE THREAD

**Issue by dannellyz** [xavctn/img2table#39]
I get a type error coming from the following stack:
File "/Users/Library/Python/3.9/lib/python/site-packages/img2table/tables/processing/bordered_tables/lines.py", line 133, in remove_word_lines
    df_lines = (pl.from_dicts(dicts=[line.dict for line in lines])
TypeError: from_dicts() got an unexpected keyword argument 'dicts'

Seems like the keyword may need to be data but have not seen anyone else have this issue?

**Comment by xavctn** [comment]
Hi,

Seems like polars realeased a new [update](https://github.com/pola-rs/polars/releases/tag/py-0.17.0) with some breaking changes. I'm gonna check it and make relevant modifications.

**Comment by dannellyz** [comment]
Amazing thanks!
