### ISSUE TITLE
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by tastopesato** [xavctn/img2table#48]
Hi @xavctn,  
I'm tryng to capture data directly from PDF, usign PaddleOCR as engine. If i try to capture from Image instead, it woks.
The exception was raised when i try to convert in excel with to_xlsx function, and with extract_tables function too.
It seems to be polars related, maybe. 

The exception was raised in ocr.data at line 150. The code is
`for rec in df_text_parent.collect(streaming=True).to_dicts():`

Here is my code for testing it:
`ocr = PaddleOCR(lang='it')`
`doc = PDF('test.pdf')`
`doc.to_xlsx(dest= 'result/test.xlsx',`
`            ocr=ocr,`
`            implicit_rows=True,`
`            borderless_tables=False,`
`            min_confidence=50)`

my environment is:
 - python: 3.10.11
 - img2table: 0.1.1
 - PaddleOCR: 2.6.1.3
 - polars: 0.17.11
 
I can send you the test PDF if you need

**Comment by xavctn** [comment]
Hi,
Yep it seems like there is a bug. Might be related to polars or by myself not catching some corner cases 😃 
I would appreciate if you can send me the file in order for me to identify and fix this bug.

**Comment by tastopesato** [comment]
> Hi, Yep it seems like there is a bug. Might be related to polars or by myself not catching some corner cases 😃 I would appreciate if you can send me the file in order for me to identify and fix this bug.
> 
> It might be related to the fact that, for native PDFs, PyMuPDF is used instead of the OCR for text retrieval

Sure. how can i send it?

**Comment by xavctn** [comment]
You can send it by email at xav.canton@gmail.com

**Comment by tastopesato** [comment]
> You can send it by email at [xav.canton@gmail.com](mailto:xav.canton@gmail.com)

Ok, sent. Thanks a lot.

**Comment by xavctn** [comment]
Will take a look at it this weekend

**Comment by xavctn** [comment]
I have fixed the error, should not be happening anymore.
Somehow, your tables are not detected in the document you sent because the lines are too faint I think

**Comment by tastopesato** [comment]
> I have fixed the error, should not be happening anymore.
> Somehow, your tables are not detected in the document you sent because the lines are too faint I think

Thank you!!! I will check asap!

**Comment by tastopesato** [comment]
@xavctn, 
I tried and now everything works! Thx for patching
