### ISSUE TITLE
exceptions.ShapeError: unable to vstack, dtypes for column "parent" don't match: `str` and `bool`

### ISSUE THREAD

**Issue by tastopesato** [xavctn/img2table#50]
The error occurr when trying to extract tables from multi page pdf with tesseract engine. It seems like #48

**Comment by xavctn** [comment]
I will enforce a schema when creating the dataframe from an OCR.
Should get rid of this issue.

**Comment by xavctn** [comment]
I was not able to reproduce the issue but I made some changes in order to enforce a consistent schema between dataframes that are concatenated that should resolve this error.
