### ISSUE TITLE
To add a custom ocr

### ISSUE THREAD

**Issue by VISHNUPRASAD-K-G** [xavctn/img2table#51]
For my mini project related work i built a custom OCR model,can i add/integrate that model to paddle of this img2table library?

**Comment by xavctn** [comment]
Hi,

You can check #47 where I explained quickly how to use a custom OCR with the library.

**Comment by VISHNUPRASAD-K-G** [comment]
can you please say where the prediction of values in each cell of table happens?

**Comment by xavctn** [comment]
It is in the code of the OcrDataframe class [here](https://github.com/xavctn/img2table/blob/main/src/img2table/ocr/data.py#L90)

**Comment by VISHNUPRASAD-K-G** [comment]
Thankyou
