### ISSUE TITLE
Extracting data from cells having more space between lines 

### ISSUE THREAD

**Issue by akshayrakate** [xavctn/img2table#53]
I am trying to extract the data from the table image as shown below
![Sample table ](https://github.com/xavctn/img2table/assets/87716311/154e12b3-331e-4e68-84bf-342e4e4dde89)

But the result cells are as shown below, here number denote cell number detected by img2table package. 
![sample_table_cells](https://github.com/xavctn/img2table/assets/87716311/f68b0fc1-8bef-407a-b78a-27c099c79315)

and the resulting dataframe I got is 
![sample_image_result_dataframe](https://github.com/xavctn/img2table/assets/87716311/c22fbd34-eb9d-42d8-a1b2-041dbc5b42b0)

How can I tune the functions of img2table package such that I get exact table as output dataframe ?

**Comment by xavctn** [comment]
Hi,

Can you try to set the parameter `implicit_rows` to `False` ?
It should fix this king of behavior.

Maybe this must be set to `False` by default

**Comment by xavctn** [comment]
In order to avoid those kind of confusion, the `implicit_rows` parameter is now set to `False` by default
