### ISSUE TITLE
manually provide textract output

### ISSUE THREAD

**Issue by joechen018** [xavctn/img2table#54]
Is there a way for me to provide the AWS textract OCR output instead of having img2table call it again? (https://github.com/xavctn/img2table/blob/main/src/img2table/ocr/aws_textract.py#L88)

I'm already calling AWS Textract independently elsewhere and would like to not have to call it twice to save costs.

Alternatively, is there a way for img2table to provide the raw Textract output?

**Comment by xavctn** [comment]
Hi,
I have not really designed anything in the library for this but it could be done.

Something like this is possible:

>     from img2table.document import Image
>     from img2table.ocr import TextractOCR
>     import polars as pl
> 
>     # Load image
>     doc = Image("img.png")
> 
>     # Mock OCR
>     mock_ocr = TextractOCR(aws_access_key_id="*",
>                            aws_secret_access_key="*",
>                            aws_session_token="*",
>                            region="*")
> 
>     # Parse textract output
>     doc.ocr_df = OCRDataframe(df=pl.LazyFrame(data=mock_ocr.map_response(response=textract_output,
>                                                                          image=list(doc.images)[0],
>                                                                          page=0)))
> 
>     # Extract tables
>     tables = doc.extract_tables(ocr=mock_ocr,
>                                 implicit_rows=False,
>                                 borderless_tables=False)`

No calls to Textract will be made and the `textract_output` should be a dictionnary such as [this one](https://github.com/xavctn/img2table/blob/main/tests/_mock_data/textract.json)
