### ISSUE TITLE
confidence score for table

### ISSUE THREAD

**Issue by joechen018** [xavctn/img2table#55]
Sometimes tables are extracted even though there are no tables in the image. For context, I'm testing on a document where there are some noisy vertical lines due to streaks from a fax machine. Is there a way to generate a confidence score for how likely the extracted table is actually a table? Or are there any parameters I can try adjusting to make the extraction process more "strict"?

**Comment by xavctn** [comment]
As of now, the whole algorithm is based on the Hough transform and is deterministic so I do not have any confidence score.
As you said, it might be possible to "score" tables based on aligment of content, text not intersecting with lines/cells...

However, it will require quite a lot of testing before creating a proper and reliable measure
