### ISSUE TITLE
PDFOcr Used by default, creates unwanted behaviour 

### ISSUE THREAD

**Issue by TowelDude** [xavctn/img2table#58]
Hey!
The pdf's I want to scan, contains characters in Hebrew, which are not supported by PDFOcr's backbone (Returns characters as question marks)
Therefore, I wanted to use GCP's `VisionOCR` that handles hebrew perfectly.
The following code will still use the default PDFOcr and ignore the VisionOCR instance I passed.
```python
from img2table.document import PDF
from img2table.ocr import VisionOCR

ocr = VisionOCR(timeout=25)

doc = PDF("test.pdf", [0])
tables = doc.extract_tables(ocr=ocr, min_confidence=70)
```

## Suggested Fix
Add to[ `PDF.extract_tables` ](https://github.com/xavctn/img2table/blob/8fff7c2fa8f22ca4d667e759315f1ea5641b16e4/src/img2table/document/pdf.py#LL66C6-L66C6
) argument `force_ocr=False`
Then, add a check before using the default `PdfOCR`

Then, in [`Document.extract_tables`](https://github.com/xavctn/img2table/blob/8fff7c2fa8f22ca4d667e759315f1ea5641b16e4/src/img2table/document/base/__init__.py#L66) add a check for `force_ocr and ocr is None` and throw exception if needed.

Let me know if this is acceptable, I can create the PR.
Thanks

**Comment by xavctn** [comment]
Hello,

Yep, it seems that PyMuPDF (the PDF library used) has some issues with non latin characters. I also had some feedback about some Indian dialects not being processed properly.

I will implement an option to bypass text extraction from the OCR and will include it in the next release.

**Comment by xavctn** [comment]
I have added a `pdf_text_extraction` parameter to the `PDF` class that allows you to bypass text extraction from the PDF file.
It is available in the latest release that I just published
