### ISSUE TITLE
Tesseract with venv jupyter notebooks

### ISSUE THREAD

**Issue by Silviculturalist** [xavctn/img2table#63]
Hey!

Many thanks for making this package,  I think it could be nice to use to digitize tables from old books which I use a lot.

I'm trying to get this set up with jupyter notebooks and python, but it seems like an error is thrown while trying to run this in a notebook. Is this particular to a venv? If I open powershell and run a subprocess command to check a version is returned for tesseract return code is 0 and everything looks like it works.

https://github.com/xavctn/img2table/blob/58152164a9d711e6caa1765d351bd899b995d4d9/src/img2table/ocr/tesseract.py#L54

tesseract also seems to be correctly installed, can be called straight from powershell console. 
available packages in venv: ipykernel, img2table, pytesseract, tesseract, numpy, pandas...

I've attached an example of what a cut-out of one of the tables can look like. (Swedish), Yield tables for Norway Spruce.

![G28_4](https://github.com/xavctn/img2table/assets/52540997/37d929af-be95-4a4b-a66c-c8765a744347)

**Comment by xavctn** [comment]
Hi,

I have run it with Tesseract on a notebook without any issues. Are you sure that Tesseract has been included in your PATH ?

Moreover, I am fairly sure that my algorithm will not be working on the table example you provided. The table elements are too cramped for the method I've implemented. You may try other libraries, I've listed examples at the end of the readme
