### ISSUE TITLE
WARNING: img2table 1.0.1 does not provide the extra 'paddle-gpu'

### ISSUE THREAD

**Issue by Wyzix33** [xavctn/img2table#64]
when i run `!pip install img2table[paddle-gpu]` on colab, is this normal?

**Comment by xavctn** [comment]
Hi,

Nope, I checked and there is a bug. I will fix it and include it in the next release

**Comment by xavctn** [comment]
It is now fixed in the newest release.
The syntax is now `pip install img2table[paddlegpu]`. I guess the dash was messing up this thing.
