### ISSUE TITLE
How do i access ExtractedTable objects's value

### ISSUE THREAD

**Issue by cody-creunies** [xavctn/img2table#67]
Let say i used the extract_tables() function to extract out the structure of the table and it returns a img2table.tables.objects.extraction.ExtractedTable .

Here comes the question on ,how can i acquire just the shape value of the extracttable object? 
[ExtractedTable(title=None, bbox=(10, 8, 745, 314),shape=(6, 3)),
 ExtractedTable(title=None, bbox=(936, 9, 1129, 111),shape=(2, 2))]
 
Required output : (6,3) /(2,2)

**Comment by xavctn** [comment]
There is a pandas DataFrame representation of the table so you can just get its shape `table.df.shape`
