### ISSUE TITLE
OS Error : OSError: Tesseract not found in environment. Check variables and PATH

### ISSUE THREAD

**Issue by som21302** [xavctn/img2table#68]
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11532\2676680553.py in <module>
----> 1 ocr = TesseractOCR()
      2 
      3 # Define image
      4 img = Image(src="C:\\Users\\mishr\\Music\\test\\Capture2.png")

~\anaconda3\lib\site-packages\img2table\ocr\tesseract.py in __init__(self, n_threads, lang, psm, tessdata_dir)
     54         cmd_tess = subprocess.run("tesseract --version", env=self.env, shell=True)
     55         if cmd_tess.returncode != 0:
---> 56             raise EnvironmentError("Tesseract not found in environment. Check variables and PATH")
     57 
     58         # Check if requested languages are available

OSError: Tesseract not found in environment. Check variables and PATH

how to install tesseract-ocr in jupyter notebook

**Comment by xavctn** [comment]
Hello,
In order to use the library with Tesseract, it has to be installed beforehand with the desired language files. The package is just calling Tesseract with a shell command, that's about it.

You can verify is Tesseract is properly installed by running `tesseract --version` in your terminal

**Comment by som21302** [comment]
Thanks! for your reply sir,
But when I was using google colab then same error has occured and at that time I have installed tesseract manually and it worked.
but in jupyter notebook I don't know how to install it.

**Comment by xavctn** [comment]
https://tesseract-ocr.github.io/tessdoc/Installation.html
