### ISSUE TITLE
Not getting desired result for my PDF and images

### ISSUE THREAD

**Issue by som21302** [xavctn/img2table#73]
Hi @xavctn,
Thanks for making this library. This working well for normal pdf.
But for my pdf it is not working well. It is not able to differentiate two rows and take it as one row followed by 'backslash n(/n)'.

here is some sample images with result

![Capture_result](https://github.com/xavctn/img2table/assets/48521929/2ac1f15e-3c0c-443a-8b5c-dc41798bdaec)
![Capture1_result](https://github.com/xavctn/img2table/assets/48521929/2f7e566f-adab-4da7-8ea3-712ccdccc066)
![Capture4_result](https://github.com/xavctn/img2table/assets/48521929/d2834fee-cbd9-48a0-ae60-b64f94dd7fb8)
![Capture5_result](https://github.com/xavctn/img2table/assets/48521929/a0715496-6057-4d15-aba6-0409a87ebb19)
![Capture8_result](https://github.com/xavctn/img2table/assets/48521929/f0e65602-a8ed-49c1-8c6b-b022142e5602)
![Capture9_result](https://github.com/xavctn/img2table/assets/48521929/b086c333-0b61-47a3-b703-48cf817e4fc3)

Please give some suggestion to get desire result.

**Comment by xavctn** [comment]
As of now, there is not really anything you can do to fix it.
I will make some evolutions on the library code to try to improve several cases such as yours  but I can not guarantee anything as of now
