### ISSUE TITLE
Expose image processing parameters

### ISSUE THREAD

**Issue by thokari** [xavctn/img2table#74]
In some files, notably in the `tables/processing` package, there are magic numbers. Maybe we could work on naming them and exposing them as parameters?

**Comment by thokari** [comment]
I agree. But consider a table that has columns detected where there are none, possibly because of handwritten content, or letters that are well aligned.

So it would be nice to have a single parameter, between 0 and 1, which represents "line confidence cutoff", where settting it to a low value would include all lines, and setting it to a high value would only include "important" lines.

I am thinking about two ways of measuring this "confidence".

1. Using image processing parameters, specifically the "rho" and "theta" parameter of this function:
https://github.com/xavctn/img2table/blob/053c05aa9c3d7d3309527aef92aef68470631ca0/src/img2table/tables/processing/bordered_tables/lines.py#LL253C46-L253C46github.com/xavctn/img2table/blob/053c05aa9c3d7d3309527aef92aef68470631ca0/src/img2table/tables/processing/bordered_tables/lines.py#L253

2. By calculating how much of the table a line is spanning. If a line doesn't cross the whole table, it should have lower confidence, be ignored according to the cutoff, and its neighboring cells be joined.

The second option would also be possible after extracting tables, but it requires recomputing a lot of information,
Consider this example document:
![image](https://github.com/xavctn/img2table/assets/6663430/ea6cb48e-ad3d-44a9-9c36-66a4a67a5b82)

**Comment by xavctn** [comment]
> So it would be nice to have a single parameter, between 0 and 1, which represents "line confidence cutoff", where settting it to a low value would include all lines, and setting it to a high value would only include "important" lines.

That might be an option, I can possibly create a kind of "empiric" scoring taking into account several factors: line span, if the line is crossing a word or not...

> Alternatively, if image processing parameters where exposed, specifically the "rho" and "theta" parameter of this function, this might also be helpful for cases like this.

Those parameters do not have a great impact. The threshold value is much more important for line confidence / line detection in the Hough transform.

I will take a look at the implementation of a first version of a "line confidence score" and check if it can be relevant when I have time

**Comment by thokari** [comment]
Removing lines that are crossing words is a good idea.
By the way, is there an option with your library to provide the OCR text externally, as alternative to `ocr=None`?

We already have OCR in our pipeline, so if possible we would like to re-use the result.

**Comment by xavctn** [comment]
Natively, no but it can be done.

Basically, you will have to map your OCR results into a polars dataframe and create an [OCRDataframe](https://github.com/xavctn/img2table/blob/main/src/img2table/ocr/base.py#L10) instance. You will find examples of this implementation if you check files related to the supported OCR solutions in the ocr section of the library.

After that, a "pseudo" implentation would look like this :

``` python
# Mapping of your raw ocr to a polars dataframe
polars_ocr_df = map_ocr(raw_ocr)

# Create OCRDataframe instance
ocr_df = OCRDataframe(df=polars_ocr_df)

# Create a document instance: Image or PDF
doc = Image(src="..")
doc.ocr_df = ocr_df

tables = doc.extract_tables(ocr=None, ...)
```
With this, it will skip the OCR part and use your provided OCR to create resulting tables
