### ISSUE TITLE
CV2 Assertion error in image without text

### ISSUE THREAD

**Issue by thokari** [xavctn/img2table#75]
Just noticed, that if an image does not contain text, CV2 throws an assertion error on this line:

```
        # Mask on areas with dark background
        blur_size = max(int(2 * char_length) + 1 - int(2 * char_length) % 2, 1) if char_length else 11
>       blur = cv2.medianBlur(img, blur_size)
E       cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/median_blur.simd.hpp:241: error: (-215:Assertion failed) k < 16 in function 'medianBlur_8u_O1'
```
Not a big problem if one knows what the problem is, but the message isn't quite clear.
But it is slightly unexpected, also because I am not doing any OCR.

**Comment by xavctn** [comment]
This is probably due to an issue with a kernel too large, not really specific to an image without text as mentionned here https://stackoverflow.com/questions/55968813/medianblur-calculate-max-kernel-size.

I will check and might implement a hard limit on kernel sizes
