### ISSUE TITLE
Different results on similar images

### ISSUE THREAD

**Issue by thokari** [xavctn/img2table#82]
Hi, 
we have several pre-processing steps in our system, that might change the scaling of images, de-rotate, de-skew them, or make changes to the color palette. I would like to show you a case where the same image leads to quite different results.
The first image is unprocessed and tables get recognized very well. The second image is - despite its much lower file size - scaled down a little bit, from a width 1653 to a width of 1500 pixels, and the detection is seemingly quite a bit worse.

I can send you the examples, if you like.

Do you have any thoughts on this?

**Comment by xavctn** [comment]
Hello,

I have worked on this topic and more specifically document layout analysis in order to be able to get a better segmentation of table areas in the image  #105.

The table detection should now be more accurate and consistent, even though it is still not 100%.
