### ISSUE TITLE
OverlappingRange Exception when Converting PDF to Excel

### ISSUE THREAD

**Issue by AvasavA** [xavctn/img2table#84]
Hello,

I've been using the img2table library to convert PDFs into Excel files, and I've encountered a problem. When running the to_xlsx method, I receive an OverlappingRange exception from the xlsxwriter library. The specific error message is:

xlsxwriter.exceptions.OverlappingRange: Merge range 'L12:Q16' overlaps previous merge range 'L9:N12'.

This error suggests that the library is trying to merge cells in Excel that are already part of another merged region. This happens even after I've cropped the PDF to avoid potential issues with certain regions. The PDF I'm working with is a schematic with various tables.

To try and resolve this issue, I've added a step to my processing where I crop the outer frame of the PDF, as I suspected that the library might be detecting it as a table and this was causing the error. This approach seemed to work sometimes but not always, so it's not a reliable solution.

Here is the code I've been using and a sample pdf i am working on:

[H60NDA10BR001  1.pdf](https://github.com/xavctn/img2table/files/12038775/H60NDA10BR001.1.pdf)

`
import os
import cv2
import tkinter as tk
from tkinter import filedialog
from PIL import Image
import numpy as np
from pdf2image import convert_from_path
import img2table
from img2table.document import Image as Img2TableImage
from img2table.ocr import PaddleOCR

ocr = PaddleOCR(lang="en") 

poppler_path = r"C:\Users\alchayah\Desktop\JustInputs\poppler-23.05.0\Library\bin"

comment # Define the fraction of the image you want to crop
comment  # These values should be between 0 and 1
crop_fraction_y = 0.024  # Crop 10% off the top and bottom
crop_fraction_x = 0.017  # Crop 10% off the left and right

def main():
    # Open file dialog to select input PDF
    input_pdf_path = filedialog.askopenfilename( 
        title='Select input PDF', filetypes=[
            ('PDF Files', '*.pdf')  
        ]
    )

    if not input_pdf_path:
        print("No input PDF selected. Exiting.")
        return

    # Open directory dialog to select output directory    
    output_dir = filedialog.askdirectory(title='Select output directory')

    if not output_dir:
        print("No output directory selected. Exiting.")
        return

    # Convert the PDF to images
    images = convert_from_path(input_pdf_path, poppler_path=poppler_path)

    for i, image in enumerate(images):
        # Convert PIL Image to OpenCV image (numpy array)
        open_cv_image = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

        # Get the dimensions of the image
        height, width, _ = open_cv_image.shape

        # Calculate the cropping coordinates
        y = int(height * crop_fraction_y)
        h = height - 2*y  # Subtract twice the margin to get the height of the central part
        x = int(width * crop_fraction_x)
        w = width - 2*x  # Subtract twice the margin to get the width of the central part

        cropped = open_cv_image[y:y+h, x:x+w]

        # Convert the cropped image back to a PIL Image
        cropped_pil = Image.fromarray(cv2.cvtColor(cropped, cv2.COLOR_BGR2RGB))

        # Save the cropped image to a file
        cropped_image_path = os.path.join(output_dir, f'cropped{i}.png')
        cropped_pil.save(cropped_image_path)

        # Create an img2table Image object
        img2table_image = Img2TableImage(src=cropped_image_path)

        # Export to Excel
        output_xlsx_path = os.path.join(output_dir, f'output{i}.xlsx')
        
        img2table_image.to_xlsx(
            output_xlsx_path, 
            ocr=ocr,
            implicit_rows=False, 
            borderless_tables=False,
            min_confidence=50
        )
        
        print(f"Output saved to {output_xlsx_path}")

if __name__ == "__main__":
    main()

`

Could you please assist me in understanding why this error is occurring and how it might be resolved? Any assistance you could provide would be greatly appreciated.

**Comment by xavctn** [comment]
Hi,
Thanks for the feedback.

The error was on my side and the handling of merged cells when creating the XLSX file. I have fixed the issue and I will include it in the next release.
