### ISSUE TITLE
Skipping Text in Complex Table

### ISSUE THREAD

**Issue by parth-jr** [xavctn/img2table#86]
I am working with a complex table and the script seems to be skipping the "SKIPPED" item in the example I shared.

![image](https://github.com/xavctn/img2table/assets/64888449/7e634b84-7d91-4c47-8cf2-b2131fb906d7)

Moreover the last 2 columns of the header row are being merged with a '\n' leading to the output looking like this

![image](https://github.com/xavctn/img2table/assets/64888449/e2a9aa05-8cea-4ff7-84b8-529815260622)

**Comment by xavctn** [comment]
Hello,
It seems like some lines in your input image are not properly detected, which leads to the resulting output.

However, without your input, I won't be able to replicate the issue and investigate

**Comment by xavctn** [comment]
I took a look at it.
To explain it simply, the minimum length of lines that are detected (in order to create tables) is based on the median of the distance between consecutive rows. In your case, this distance is too large compared to the height of the header and that is why the lines in the header are not detected.

This is a specific case that I won't fix because it would risk to deteriorate the accuracy of the algorithm on most cases if I do so.

**Comment by parth-jr** [comment]
> I took a look at it. To explain it simply, the minimum length of lines that are detected (in order to create tables) is based on the median of the distance between consecutive rows. In your case, this distance is too large compared to the height of the header and that is why the lines in the header are not detected.
> 
> This is a specific case that I won't fix because it would risk to deteriorate the accuracy of the algorithm on most cases if I do so.

Is it possible for me to modify it on my end locally? If so, could you point me to the parameter to modify.

**Comment by xavctn** [comment]
Yep, the parameter value is set here https://github.com/xavctn/img2table/blob/main/src/img2table/tables/image.py#L66

**Comment by xavctn** [comment]
You might have to lower the parameter defined just above as well

**Comment by parth-jr** [comment]
> You might have to lower the parameter defined just above as well

Got it, Thank you so much!

**Comment by parth-jr** [comment]
Hey,

Tuning above-mentioned parameter worked well for the table elements, but the column names still seemed to be missed, they are being recognized as a part of the table title. 

Is there any other parameter to further reduce the distance threshold?
