### ISSUE TITLE
OSError: Tesseract not found in environment. Check variables and PATH

### ISSUE THREAD

**Issue by ivantan4ik** [xavctn/img2table#88]
def line(src):
    ocr = TesseractOCR(n_threads=1,
                       lang="rus",
                       psm=11,
                       tessdata_dir=r"C:\Program Files\Tesseract-OCR\tessdata")
    doc = Image(src)
    doc.to_xlsx(dest='1.xlsx',
                ocr=ocr,
                implicit_rows=False,
                borderless_tables=False,
                min_confidence=50)

**Comment by xavctn** [comment]
You have to update your environment variables on Windows.
https://linuxhint.com/install-tesseract-windows/
