### ISSUE TITLE
ImportError: cannot import name 'EasyOCR' from 'img2table.ocr'

### ISSUE THREAD

**Issue by SelvakumarKrishnamoorthy** [xavctn/img2table#89]
Hi,

I am using the version img2table[easyocr]==1.0.7

and when i try to invoke the easyocr 

from img2table.ocr import EasyOCR
easyocr = EasyOCR(lang=["en"])

i am getting the following error 
cannot import name 'EasyOCR' from 'img2table.ocr' (<localpath>/lib/python3.10/site-packages/img2table/ocr/__init__.py)

**Comment by xavctn** [comment]
You should have easyocr installed in order to use it.
You can run `pip install img2table[easyocr]`

**Comment by GamovSP** [comment]
Same thing with PaddleOCR, even with it being installed with pip

**Comment by GamovSP** [comment]
Same thing with PaddleOCR, I installed paddle, but can't invoke it.

**Comment by xavctn** [comment]
I have done some checks.
- EasyOCR works as intended when installed properly from what I tried
- PaddleOCR has some issues on some platforms It can be solved by installing `paddlepaddle==2.4.2`

I will update the paddlepaddle version in the project
