### ISSUE TITLE
Automatic setting borderless_tables flag

### ISSUE THREAD

**Issue by akshayrakate** [xavctn/img2table#90]
Hi, I have a set of images that contains **border and borderless tables**. Actually, I am passing cropped table image region to img2table for extraction of data. But every time I have to set borderless_table flag true or false depending upon type of table. Is there any way to **set borderless_tables flag True/False automatically?**

![image](https://github.com/xavctn/img2table/assets/87716311/ec946fac-24b6-4b8e-ba41-9d56ba621716)

**Comment by xavctn** [comment]
I think that the effect of the parameter is not clear:
- `borderless_tables=False`: only bordered tables are detected by the algorithm
- `borderless_tables=True`: borderless tables are detected by the algorithm **on top of** bordered tables

So, I you set it to `True` all the time, the only difference would be that, when there are no borderless tables/only bordered tables in your document, it might detect some crap on top of your actual tables

**Comment by akshayrakate** [comment]
Hi xavctn, 
Thanks for your response. It's working. You can close the issue. 👍🏻

**Comment by akshayrakate** [comment]
Hi xavctn, 
Thanks for your response. It's working.
