### ISSUE TITLE
ModuleNotFoundError: 'img2table' is not a package

### ISSUE THREAD

**Issue by Frkchs** [xavctn/img2table#91]
Hi, I tried to install but I still get the same error:

My code file "img2table.py":
```python
from img2table.document import Image
```

Ouptut
```bash
# python3.8 img2table.py
Traceback (most recent call last):
  File "img2table.py", line 1, in <module>
    from img2table.document import Image
  File "/home/.../img2table.py", line 1, in <module>
    from img2table.document import Image
ModuleNotFoundError: No module named 'img2table.document'; 'img2table' is not a package
```
I tried with :
python 3.8
python 3.7
python 3.6

The module is installed in /usr/local/lib/python3.8/dist-packages. Everything OK.
Still the same error. What am I doing wrong?
Thanks in advance to anyone who can help me

**Comment by xavctn** [comment]
This is not related to the package but it is because of your hierarchy and the way you call the python file you created.
Basically, your interpreter uses your local `img2table.py` as the reference when you try to import the package because you name it the same way as the package and the local files takes precedence.
If you rename your file, you won't have any issues.

**Comment by Frkchs** [comment]
Thanks for your reply, it works.

My code file "test_img_2_table.py":
```python
from img2table.document import Image
```

Now I get this other error:

Ouptut
```bash
Illegal instruction (core dumped)
```

I tried with :
python 3.10
python 3.8
python 3.7
python 3.6

**Comment by xavctn** [comment]
This is not a python exception.
When researching this issue on google, it seems like it is hardware related. I do not think that I can do anything about it.

**Comment by Frkchs** [comment]
For anyone encountering this issue, the error is likely caused by the lack of AVX instruction set in the processor on the machine where you are trying to install the library.

To check if AVX is present on your processor, run:

```
grep -o avx /proc/cpuinfo
```

If your processor supports AVX, the command should return an output similar to this:
```
avx
```
If you don't see any output or don't see the word "avx," it means that your processor might not support AVX instructions.
