### ISSUE TITLE
Problem using OCR with pytesseract installed

### ISSUE THREAD

**Issue by ColinFerguson** [xavctn/img2table#95]
Hi and thank you for this project, it is very useful.  I am having an issue extracting table contents via ocr.

`File ~\Anaconda3\lib\site-packages\img2table\ocr\tesseract.py:56, in TesseractOCR.__init__(self, n_threads, lang, psm, tessdata_dir)
     54 cmd_tess = subprocess.run("tesseract --version", env=self.env, shell=True)
     55 if cmd_tess.returncode != 0:
---> 56     raise EnvironmentError("Tesseract not found in environment. Check variables and PATH")
     58 # Check if requested languages are available
     59 try:

OSError: Tesseract not found in environment. Check variables and PATH`

I have tried this with both

`ocr = TesseractOCR(lang="eng")`

and

`ocr = TesseractOCR(n_threads=1, 
                   lang="eng", 
                   psm=11,
                   tessdata_dir=**PATH_TO_TESS_DATA**)`

I do have pytesseract installed and can successfully use `pytesseract.image_to_string`, which always requires me to set an env variable first `pytesseract.pytesseract.tesseract_cmd = r'**PATH_TO_TESS_EXE**'`

Any help you can give would be much appreciated.  Apologies for the naive question.

**Comment by xavctn** [comment]
Hi,
You just have to update your system variables and add Tesseract to your PATH.
You can check this [tutorial](https://linuxhint.com/install-tesseract-windows/) explaining the process.
