### ISSUE TITLE
Processing issues

### ISSUE THREAD

**Issue by YarickVodila** [xavctn/img2table#97]
After updating the version from 1.0.7 to 1.10.0, table detection has become much worse and sometimes does not detect tables

**Comment by xavctn** [comment]
Hello,
Are you able to provide exemples ?

On my end, I use a dataset of images to test the potential regressions for each version and have not seen any significant ones with the latest ones

**Comment by YarickVodila** [comment]
version 1.0.7
![image](https://github.com/xavctn/img2table/assets/90455547/95fb4182-9450-4fc5-a358-df70800ff5c1)
version 1.10.0
![Image](https://github.com/xavctn/img2table/assets/90455547/5ea799fe-f9d3-4d8f-b1ba-09282dd0ba83)
File for test
[КП Нинбо-РФ.pdf](https://github.com/xavctn/img2table/files/12343029/-.pdf)

**Comment by xavctn** [comment]
I created a new release. It should be fixed

**Comment by YarickVodila** [comment]
thanks ;)
