### ISSUE TITLE
I want to use easy ocr on different GPU

### ISSUE THREAD

**Issue by dhifafaz** [xavctn/img2table#99]
I want to use easy ocr on different GPU, is it possible?

**Comment by xavctn** [comment]
Hello,

I have not tried to use it on GPU but the [Reader](https://github.com/xavctn/img2table/blob/main/src/img2table/ocr/easyocr.py#L28) is instantiated with mostly the default arguments.

From their code, it seems that it is supposed to support usage with GPU https://github.com/xavctn/img2table/blob/main/src/img2table/ocr/easyocr.py#L28
